"use strict";
exports.id = 239;
exports.ids = [239];
exports.modules = {

/***/ 65888:
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   A: () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(96540);
var __defProp = Object.defineProperty;
var __getOwnPropSymbols = Object.getOwnPropertySymbols;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __propIsEnum = Object.prototype.propertyIsEnumerable;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __spreadValues = (a, b) => {
  for (var prop in b || (b = {}))
    if (__hasOwnProp.call(b, prop))
      __defNormalProp(a, prop, b[prop]);
  if (__getOwnPropSymbols)
    for (var prop of __getOwnPropSymbols(b)) {
      if (__propIsEnum.call(b, prop))
        __defNormalProp(a, prop, b[prop]);
    }
  return a;
};
var __objRest = (source, exclude) => {
  var target = {};
  for (var prop in source)
    if (__hasOwnProp.call(source, prop) && exclude.indexOf(prop) < 0)
      target[prop] = source[prop];
  if (source != null && __getOwnPropSymbols)
    for (var prop of __getOwnPropSymbols(source)) {
      if (exclude.indexOf(prop) < 0 && __propIsEnum.call(source, prop))
        target[prop] = source[prop];
    }
  return target;
};

const OptimizedImage = (_a) => {
  var _b = _a, {
    src,
    alt,
    width,
    height,
    loading = "lazy",
    className = ""
  } = _b, rest = __objRest(_b, [
    "src",
    "alt",
    "width",
    "height",
    "loading",
    "className"
  ]);
  return /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement(
    "img",
    __spreadValues({
      src,
      alt,
      width,
      height,
      loading,
      className
    }, rest)
  );
};
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (OptimizedImage);


/***/ }),

/***/ 72239:
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(96540);
/* harmony import */ var _OptimizedImage__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(65888);


const ExceptionSection = () => /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("div", { className: "info-section p-4 mb-4 bg-white dark:bg-gray-800 rounded shadow" }, /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("nav", { className: "mb-6" }, /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("h2", { className: "text-2xl font-bold mb-2" }, "Exception"), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("a", { href: "#exception", className: "text-blue-600 hover:underline mr-2" }, "What Is an Exception"), "|", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("a", { href: "#kind", className: "text-blue-600 hover:underline mx-2" }, "Kinds of Exception"), "|", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("a", { href: "#fix", className: "text-blue-600 hover:underline mx-2" }, "How to fix"), "|", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("a", { href: "#example", className: "text-blue-600 hover:underline mx-2" }, "Examples"), "|", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("a", { href: "#workshop", className: "text-blue-600 hover:underline ml-2" }, "Workshop")), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("section", null, /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("a", { id: "exception" }), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("h2", { className: "text-xl font-semibold mb-2" }, "Exception"), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("p", null, "An exception is an event, which occurs during the execution of a program, that disrupts the normal flow of the program's instructions."), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("p", null, "When an error occurs within a method, the method creates an object and hands it off to the runtime system. The object, called an exception object, contains information about the error, including its type and the state of the program when the error occurred. Creating an exception object and handing it to the runtime system is called throwing an exception.", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("em", null, "[for ", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("a", { href: "http://docs.oracle.com/javase/tutorial/essential/exceptions/index.html", target: "_blank", className: "text-blue-600 underline" }, "detail"), "]")), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("p", { className: "mt-4" }, "For example:", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), "a user might type an invalid filename;", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), "An accessed file does not exist or might contain corrupted data;", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), "a network link could fail;", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), "\u2026", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), "Circumstances of this type are called exception conditions in Java and are represented using objects (All exceptions descend from the java.lang.Throwable).", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), "Consider the code that cause an exception:", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("div", { className: "flex justify-center" }, /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement(_OptimizedImage__WEBPACK_IMPORTED_MODULE_1__/* ["default"] */ .A, { src: "/media/exception.webp", alt: "exception code example", className: "my-4", width: 400, height: 250, loading: "lazy" })), "At the row 4, the method main causes one error and this method creates an exception object, its type is ArithmaticException. And then JVM will throw it to the method main. Because the method main we do nothing to control this error, the output looks like this.", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), "when the error occurs at the row 4, the statement at the row 5 is dismissed."), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("a", { id: "kind" }), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("h2", { className: "text-xl font-semibold mb-2 mt-8" }, "Kinds of Exception"), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("span", { className: "font-semibold" }, "Checked exception"), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), "Checked exceptions are the exceptions that are checked at compile time. You must handle them by either the try-catch mechanism or the throws-declaration mechanism.", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("em", null, "for example:"), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("div", { className: "flex justify-center" }, /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement(_OptimizedImage__WEBPACK_IMPORTED_MODULE_1__/* ["default"] */ .A, { src: "/media/exception2.webp", alt: "checked exception example", className: "my-4", width: 400, height: 250, loading: "lazy" })), "In the above example, the method FileReader() is throwing an exception to here. So, you must use try-catch mechanism or throws mechanism to handle.", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("span", { className: "font-semibold" }, "Unchecked exception"), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), "An unchecked exception is an exception that occurs at the time of execution. These are also called as Runtime Exceptions. The program won\u2019t give a compilation error. Most of the times these exception occurs due to the bad data provided by user during the user-program interaction.", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("em", null, "for example:"), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("div", { className: "flex justify-center" }, /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement(_OptimizedImage__WEBPACK_IMPORTED_MODULE_1__/* ["default"] */ .A, { src: "/media/exception1.webp", alt: "unchecked exception example", className: "my-4", width: 400, height: 250, loading: "lazy" })), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), "If you have declared an array of size 5 in your program, and trying to call the 6th element of the array then an error occurs.", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("em", null, "[for ", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("a", { href: "https://stackify.com/types-of-exceptions-java/", target: "_blank", className: "text-blue-600 underline" }, "detail"), "]"), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("a", { id: "fix" }), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("h2", { className: "text-xl font-semibold mb-2 mt-8" }, "How to fix"), "We can use try-catch mechanism or throws mechanism to handle to avoid this error.", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("span", { className: "font-semibold" }, "try-catch mechanism"), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), "Consider the flow and syntax:", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("div", { className: "flex justify-center" }, /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement(_OptimizedImage__WEBPACK_IMPORTED_MODULE_1__/* ["default"] */ .A, { src: "/media/exception3.webp", alt: "try-catch syntax", className: "my-4", width: 400, height: 250, loading: "lazy" })), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), "The ", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("em", null, "try"), " statement allows you to define a block of code to be tested for errors while it is being executed.", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), "The ", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("em", null, "catch"), " statement allows you to define a block of code to be executed, if an error occurs in the try block.", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), "The ", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("em", null, "finally"), " statement lets you execute code, after try...catch, regardless of the result.", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("div", { className: "bg-yellow-200 dark:bg-yellow-700 text-yellow-900 dark:text-yellow-100 border-l-4 border-yellow-500 dark:border-yellow-400 px-4 py-2 my-4 rounded shadow-sm font-medium" }, /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("span", { className: "font-bold" }, "Note:"), " You cannot use ", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("span", { className: "font-mono" }, "finally"), " without a ", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("span", { className: "font-mono" }, "try"), " block. The ", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("span", { className: "font-mono" }, "finally"), " block is optional."), "In the example ", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("b", null, "DemoException2"), ", we will edit", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("div", { className: "flex justify-center" }, /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement(_OptimizedImage__WEBPACK_IMPORTED_MODULE_1__/* ["default"] */ .A, { src: "/media/exception5.webp", alt: "DemoException2 example", className: "my-4", width: 400, height: 250, loading: "lazy" })), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("p", null, 'When the program runs to the row 14, if the file name "computer.txt" does not exist then an exception object is created (its type is FileNotFoundException) by the method main and JVM will throw the object to catch block, the variable e is used to store the address of the object. In the catch block, you can use the variable e to get error information.', /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("b", null, "The Output will be :"), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), "something are wrong", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), "try-catch is finished", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null)), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("p", null, "In the example ", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("b", null, "ExceptionDemo_1"), ", we will edit", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null)), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("div", { className: "flex justify-center" }, /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement(_OptimizedImage__WEBPACK_IMPORTED_MODULE_1__/* ["default"] */ .A, { src: "/media/exception4.webp", alt: "ExceptionDemo_1 example", className: "my-4", width: 400, height: 250, loading: "lazy" })), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("p", null, "When you try to get 6th elements, an exception object is created (its type is ArrayIndexOutOfBoundsException). JVM will throws the object to catch block.", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("b", null, "The output will be:"), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), "1,2,3,4,5,something are wrong", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), "try-catch is finished", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null)), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("span", { className: "font-semibold" }, "throws mechanism"), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), "In the example ", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("b", null, "DemoException2"), ", the error occurs in the main, to fix a checked exception we use ", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("b", null, "throws"), " keyword. We will edit:", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("div", { className: "flex justify-center" }, /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement(_OptimizedImage__WEBPACK_IMPORTED_MODULE_1__/* ["default"] */ .A, { src: "/media/exception6.webp", alt: "throws mechanism example", className: "my-4", width: 400, height: 250, loading: "lazy" })), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("b", null, "The output will be:"), ' something are wrong if the file name "computer.txt" does not exist.', /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("a", { id: "example" }), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("h2", { className: "text-xl font-semibold mb-2 mt-8" }, "Examples"), 'The code below to print out "age is 20 or older" if age is below 20 or input a text.', /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("div", { className: "flex justify-center" }, /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement(_OptimizedImage__WEBPACK_IMPORTED_MODULE_1__/* ["default"] */ .A, { src: "/media/exception7.webp", alt: "age example code", className: "my-4", width: 400, height: 250, loading: "lazy" })), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), 'When the code runs to the row 20, if you input a text "hello" then this method will create an exception object and JVM will throw it to the catch block to handle. The output will be :', /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("div", { className: "flex justify-center" }, /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement(_OptimizedImage__WEBPACK_IMPORTED_MODULE_1__/* ["default"] */ .A, { src: "/media/exception8.webp", alt: "output for hello input", className: "my-4 inline", width: 400, height: 250, loading: "lazy" })), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), "If you input 18 then the statement ", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("b", null, "throw new Exception()"), " will create an exception object. This object will be thrown to the catch block. The output will be:", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("div", { className: "flex justify-center" }, /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement(_OptimizedImage__WEBPACK_IMPORTED_MODULE_1__/* ["default"] */ .A, { src: "/media/exception9.webp", alt: "output for 18 input", className: "my-4 inline", width: 400, height: 250, loading: "lazy" })), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("span", { className: "font-semibold mt-8" }, "Summary"), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("br", null), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("ul", { className: "list-disc list-inside mb-4" }, /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("li", null, "A try block is always followed by a catch block, which handles the exception that occurs in associated try block."), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("li", null, "A single try block can have multiple catch blocks associated with it. see ", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("em", null, /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("b", null, /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("a", { href: "https://docs.oracle.com/javase/7/docs/technotes/guides/language/catch-multiple.html", target: "_blank", className: "text-blue-600 underline" }, "catching multiple exceptions in java.")))), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("li", null, "A try statement may be nested inside either the try or catch block of another try statement. see ", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("em", null, /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("b", null, /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("a", { href: "https://beginnersbook.com/2013/04/nested-try-catch/#:~:text=When%20a%20try%20catch%20block,that%20that%20catch%20block%20executes.", target: "_blank", className: "text-blue-600 underline" }, "Nesting of try/catch Blocks")))), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("li", null, "When you write a method that causes an exception. If you do not want to handle this error you can throw it to another method to handle the error by using throws keyword"), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("li", null, "You can create your own exception Classes, see ", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("a", { href: "https://www.javatpoint.com/custom-exception", target: "_blank", className: "text-blue-600 underline" }, "Custom Exception Classes"))), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("h2", { className: "text-xl font-semibold mb-2 mt-8" }, "Course slide"), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("ul", { className: "list-disc list-inside mb-4" }, /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("li", null, /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("a", { href: "/resource/Exception Handling.pdf", download: true, className: "text-blue-600 underline" }, "Exceptions.pdf"))), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("a", { id: "workshop" }), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("h2", { className: "text-xl font-semibold mb-2 mt-8" }, "Workshop"), /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("ul", { className: "list-disc list-inside mb-4" }, /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("li", null, "Complete the ", /* @__PURE__ */ react__WEBPACK_IMPORTED_MODULE_0__.createElement("a", { href: "/workshop/workshop2.pdf", download: true, className: "text-blue-600 underline" }, "workshop2")))));
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (ExceptionSection);


/***/ })

};
;